### ISSUE TITLE
Work description

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/cityGMLto3DTiles-docker#1]
## General logic
PythonCallingDocker uses some home made [python wrappers of the docker command ](https://github.com/VCityTeam/cityGMLto3DTiles/PythonCallingDocker/docker_helper.py), named `docker_helper.py`, in order to:
1. either build or pull the required container images
2. run (in sequence or in parallel when a service is needed) containers as a workflow.

When building the images, is does so out of [local contexts located in the `Docker/` subdirectory](https://github.com/VCityTeam/cityGMLto3DTiles/tree/master/Docker). The python based Tiler code has evolved and it's [new `py3dTilers` repository avatar](https://github.com/VCityTeam/py3dtilers) now comes with its [py3dTilers-docker](https://github.com/VCityTeam/py3dtilers-docker) repository which introduces a new used case: [building a docker image out of git repository context](https://docs.docker.com/engine/reference/commandline/build/#git-repositories).

In the long run the usage of kubernetes based workflow languages (e.g. [Argo workflows](https://argoproj.github.io/argo-workflows/)) will remove the need for building the containers from within the workflow. 
Hence instead of extending `docker_helper.py` with new git-repositories-building features, we shall adopt a simplified approach and 
1. remove all image building/pulling features from  `docker_helper.py` and simplify the 
2. require the user to manually build the containers (which is one `docker` command per container that is extend [those commands](https://github.com/VCityTeam/cityGMLto3DTiles/Docker/Readme.md))

Then we shall simplify all the python workflow description by removing all the (now non available) pulling/building code.

## Tasks
- [ ] remove all image building/pulling features from [`docker_helper.py`](https://github.com/VCityTeam/cityGMLto3DTiles/PythonCallingDocker/docker_helper.py)
- [ ] deal with the consequences of the above cleanup (that clean all the python code that imported [`DockerHelperBuild`](https://github.com/VCityTeam/cityGMLto3DTiles/blob/master/PythonCallingDocker/docker_helper.py#L42) and ['DockerHelperPull'](https://github.com/VCityTeam/cityGMLto3DTiles/blob/master/PythonCallingDocker/docker_helper.py#L75)
- [ ] Import this [`UD-Reproducibility/Computations` container code](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Computations/3DTiles/ChemistryValley/DockerContext) and adapt it accordingly

## Notes
* Find out if we need a docker-compose in order to run the postgresql databases that are uses by 3DCityDB container or whether the `3DCityDB` docker container "integrates" the postgresql image. 
- [ ] import the
